version: "3.9"
services:
  blazor-demo-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/blazor-demo-debug:${TAG}
    ports:
      - 2222:2222
      - 7001:7001

  blazor-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/blazor-demo:${TAG}
    ports:
      - 7001:7001

  blazor-demo-browser-debug:
    build:
        context: .
        dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/blazor-demo-debug:${TAG}
    ports:
      - 2222:2222
      - 7001:7001
    devices:
      - /dev/gpiochip0
      - /dev/i2c-1
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - /proc/device-tree:/proc-host/device-tree:ro
    depends_on:
      - cog

  blazor-browser:
    build:
        context: .
        dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/blazor-demo:${TAG}
    ports:
      - 7001:7001
    depends_on:
      - cog

  cog:
    image: commontorizon/cog${GPU}:4-rc
    command: http://localhost:7001 -w
    #command: http://192.168.0.111:7001 -w
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty1
      - "c 4:1 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"
    depends_on:
      - weston

  weston:
    image: torizon/weston${GPU}:4-rc
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty1
      - "c 4:1 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"
